### ISSUE TITLE
Creación de prototipo no funcional provisional

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#11]

**Comment by Josdelsan** [comment]
Hay que ir planteando un prototipo no funcional general que defina una aplicación genérica centrándonos en la accesibilidad.

@rosmolarr

**Comment by rosmolarr** [comment]
Voy a buscar una buena página donde hacerlo y me pongo a ello :D

**Comment by Josdelsan** [comment]
Seguir evolucionando los mockups y buscar feedback de los clientes

**Comment by rosmolarr** [comment]
@lNoelia mañana podemos ir viendo como hacerlo

**Comment by rosmolarr** [comment]
Comprobar que contiene todas las funcionalidades de la primera iteración y añadir el diagrama de navegabilidad.

**Comment by rosmolarr** [comment]
Cambiar Bosco por Bosco global
