### ISSUE TITLE
Documento de análisis y requisitos del sistema

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#12]
SE RECOMIENDA REPASAR LOS DOCUMENTOS DE LA ASIGNATURA INGENIERÍA DE REQUISITOS IR

Este documento hereda el trabajo hecho del documento de requisitos anterior y lo hace formal para su posterior uso en el desarrollo.

Se deberá redactar un documento formal que contenga las siguientes secciones.

- **Introducción**: describir brevemente el alcance, participantes (nuestra oganización) y objetivos.
- **Arquitectura lógica del sistema**:  diagrama y descripción de la arquitectura lógica (capa de presentación, lógica de negocio, nuestros sistemas de backend y frontend serán 2 sistemas que se conectan )
- **Modelo de clases**: diagrama uml de clases y descripción (que significa cada atributo)
- **Descripción de los módulos a desarrollar**: hay que acotar el alcance de cada módulo y su funcionalidad
- **Catálogo de requisitos**: contiene las subsecciones
  - **Requisitos generales**
  - **Casos de uso**
     - Diagramas
     - Actores del sistema
     - Descripción
  - **Requisitos funcionales**
     - Requisitos de información
     - Reglas de negocio
     - Requisitos de conducta
  - **Requisitos no funcionales**
      - Requisitos de seguridad
      - Requisitos de usabilidad
  - **Restricciones técnicas**
  - **Requisitos de integración**
- **Interfaz de usuario**:hacer un diagrama en formato grafo que representa la navegabilidad entre pantallas y hacerlo aparte en formato A3 o A2 Ó hacer mockup directamente interactivo (contemplado en #11 )

Hay que dejar clara de algún modo la división de a que módulo pertenece cada elemento del documento para poder agilizar el proceso del desarrollo.

**Comment by Josdelsan** [comment]
Asignación de cada sección del documento:

- Introducción y Arquitectura lógica del sistema: @marinaramirofde @juaalvcam 
- Modelo de Clases y Descripción de módulos: @cardelbec @marolmmar1 
- Requisitos generales y Casos de uso: @olisanrod @Manueldm01 @aisqazcev 
- Requisitos func, no func, restricciones técnicas e Integración: @olisanrod @Manueldm01

**Comment by rosmolarr** [comment]
@Rick3600 @rubsuadav 
Revisar el documento y proponer los cambios necesarios
