### ISSUE TITLE
Ajustar el formato a todos los documentos

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#14]
Añadir a todos los documentos un **control de versiones**, y repasarlos para que todos tengan el mismo formato, margen, tipo de letra, pie de página, etc.

Vamos a preparar los documentos para una vez terminados podamos sacar la primera versión y subirlos al repositorio.

**Comment by Josdelsan** [comment]
Ahora hay que tener en cuenta las reglas de entrega de la documentación del entregable del martes. Habrá que intentar entregar todos los documentos que estén suficientemente presentables. Para eso hay que garantizar que siguen un formato tanto en nombre (ya se cambiara  en el pdf, y portadas)

**Comment by mansanrod4** [comment]
Ya están adaptados todos los documentos hechos hasta ahora: misma portada (falta añadir algunos campos que piden para la entrega), encabezado, índice y lista de títulos. Ahora si se quiere cambiar colores o fuentes de los títulos se puede hacer fácilmente.
