### ISSUE TITLE
Encuesta para un estudio de mercado

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#16]
Se propone realizar una encuesta de cara a pasarla por las distintas ONGs sevillanas, para que conozcan el producto que ofrecemos, mostrarles el plan de precios, e intentar saber que opinan de ello y si pagarían por una PWA de estas características. 

****
Esta tarea consistirá en los siguientes pasos:
1. **Comunicarnos** con Muller para tratar de obtener una lista con los correos electrónicos de las ONGs que quedaron descartadas de querer acceder a su propuesta (creo recordar que eran 21 las que se quedaron fuera de las 40 que contactó).
2. **Redactar** un correo genérico donde explicaremos en qué consiste nuestro proyecto, como dice Rosa, mostrando el plan de precios e intentar tener un feedback sobre su interés, si les gustaría participar, si pagarían, qué añadirían si fuese el caso de una aplicación para ellos... Podemos hacerlo de forma de correo o tal vez un cuestionario, habría que estudiarlo.
3. **Recopilar** los resultados en un documento (puede que tome más de una semana, porque depende de la frecuencia con la que respondan) y analizarlos de cara a compartir un análisis y una reflexión en alguna de las presentaciones.

**Comment by lNoelia** [comment]
La encuesta está acabada pero estoy preparando los correos ahora mismo.
