### ISSUE TITLE
Actualizar landing page

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#19]
Crear una página estática que contenga la siguiente información:

- Landing page con slogans
- Temática acorde al producto
- Plan de precios
- Explicación de los módulos
- Explicación de que hacemos en la empresa

Que sea minimalista, con fondo blanco y ligera a la vista. Los textos se especificarán más adelante.

**PARA DESPLEGAR LA PÁGINA HAREMOS UN REPO Y AUTOMATIZAMOS EL DESPLIEGUE. AVISAD A UN PM Y SE GESTIONA.**

![Image](https://user-images.githubusercontent.com/74303153/219947016-aae8f4a3-2ba0-43d2-97ff-09b4b988b973.png)

**Comment by Josdelsan** [comment]
**Esto vale como parte del plan de formación.**

Investigar sobre **React** (estructura de proyectos, que es un componente y como reutilizarlo usando variables). Vamos a usar solo React sin ningun framework específico, aún así la plantilla usa Tailwind css (necesitamos feedback si usar tailwind podría ser viable aunque no es prioritario).

A raíz de lo anterior, seguir evolucionando la página para que quede profesional e ir añadiendo información nuestra. Va a ser nuestra mejor carta de presentación a inversores (esto será un proceso iterativo incremental a lo largo del proyecto, lo ideal es que tengáis una versión funcional en **main**  una rama **develop** de pruebas)

El despliegue actual es una prueba gratuita para organizaciones en vercel, hay que evaluar pasarlo a un repo privado con un fork y hacer el despliegue desde ahí (tampoco es prioritario)

**Comment by Josdelsan** [comment]
Ahora que comenzamos el desarrollo vamos a dejar en espera esta tarea hasta que se retomen las tareas de marketing antes del lanzamiento. Se subirán los cambios que ya estén hechos.

**Comment by lNoelia** [comment]
Actualizar la landing page con las redes sociales, solucionar los errores y poner nueva información sobre por ejemplo los posibles planes de inversion

**Comment by Josdelsan** [comment]
Se ha añadido los términos y condiciones de servicio. Pensando si añadir los SLA. Se ha dejado preparado para meter los enlaces a las redes sociales. También se ha refactorizado un poco la parte del header. No se han desplegado los cambios.

**Comment by mansanrod4** [comment]
Para mejorar el SEO deberíamos añadir más caracteres al título (30-65) y la meta descripción (120-320) además de etiquetar las imágenes y los enlaces. (más info en el plan de marketing)

**Comment by Josdelsan** [comment]
Se ha desplegado la web con algunos cambios.

Para mejorar el SEO ahora el título tiene mas de 30 caracteres y la descripción más de 300. Falta revisar las imágenes para añadir títulos de descripciones, enlaces, etc.

Se ha añadido al footer los enlacer a las redes sociales y enlaces a páginas estáticas con los acuerdos a nivel de servicio (SLA) y términos de servicio (TOS).

Sería interesante poner una sección de "casos de éxito" con captura de pantallas de las web separadas de las ONG que tenemos en funcionamiento. Algo similar a los que tenemos del móvil con el logo de Aiding al inicio. Podríamos incluso mencionar a las ONG aunque para ello hay que pedir permiso. Algo al estilo "Ya confían en nosotros: ".
