### ISSUE TITLE
Evaluación de los miembros del grupo

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#26]
Se propone crear un documento describiendo como evaluar a los miembros del equipo, teniéndose en cuenta las horas trabajadas, la calidad del trabajo, la actitud, la asistencia a reuniones, así como la proactividad y la aptitud, y lo firmado en el contrato.

**Comment by lNoelia** [comment]
Se han actualizado las evaluaciones según hablamos en la reunión y además, se han añadido evaluaciones para los diferentes roles que trabajan en el proyecto

**Comment by lNoelia** [comment]
Hacer la encuesta para la evaluación de los miembros del equipo
