### ISSUE TITLE
Documento de retrospectiva

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/NGOs-documentation#27]
Análisis en profundidad de la retrospectiva, problemas que hemos tenido, evolución de los problemas ,medición de los problemas, impacto en el equipo y en el proyecto, probabilidad, problemas que no habiamos identificado ¿han ocurrido?, añadir en el las reuniones de retrospectiva.

**Comment by Josdelsan** [comment]
Adaptar la retrospectiva al feedback recibido en la clase del 15-03-2023

**Comment by lNoelia** [comment]
@aisqazcev @olisanrod ¿Podéis actualizar el estado de esta tarea? ¿Estáis teniendo algún problema? ¿Está ya acabada?

**Comment by aisqazcev** [comment]
@Rick3600 por si puedes revisar la retro

**Comment by Manueldm01** [comment]
El documento está terminado y a la espera de revisión.
