### ISSUE TITLE
Documento de calidad

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/NGOs-documentation#28]
Procesos de medicion de la calidad (medidas objetivas), metodología. calidad del software. Evaluación de la evolucion del código (code smells, bugs...)

**Comment by Josdelsan** [comment]
Darle un repaso a las métricas y ver que se puede sacar de codacy y que es lo más importante. Vamos a buscar algunas gráficas para la presentación.

**Comment by cardelbec** [comment]
He añadido una métrica objetiva que he sacado del análisis de Codacy, que es el % de issues. Las otras métricas que utiliza (complejidad y duplicaciones) no las he metido en el documento porque parece que funcionan regular, la complejidad está siempre al 0 y considera como duplicaciones lo que le da la gana. También he añadido un apartado de evolución de la calidad con las gráficas que hay en el dashboard, si puede revisarlo alguien para poder hacer los cambios cuanto antes sería ideal.

**Comment by lNoelia** [comment]
Está bien el documento Carlos, no estaría de más poner la tablita de abajo de "issues breakdown" en el que se desglosan el tipo de issues.

![Image](https://user-images.githubusercontent.com/73660773/226441393-5da4a473-93a2-4370-9703-cea9210f2d49.png)

Al final del segundo sprint la actualizamos con la nueva info y listo. 👍
