### ISSUE TITLE
Documento de riesgos

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/NGOs-documentation#29]
Tarea: realizar estimación de los riesgos, evolución, documentación de los riesgos, COMO LOS HEMOS MEDIDO y ACTUADO (medidas objetivas). Medir los planes que hemos seguido y si están haciendo efecto problemas, evolución de los problemas , medición de los problemas, impacto, probabilidad, problemas que no habíamos identificado ¿han ocurrido?

**Comment by lNoelia** [comment]
Se ha actualizado el informe de riesgos y se han preguntado al grupo algunas preguntas para evaluar el progreso de los riesgos
El domingo tendré una reunión con Celia para hacer el documento con una mayor profundidad y resolver los puntos explicados en la issue

**Comment by Josdelsan** [comment]
Actualizar el estado de los riesgos a lo largo del sprint

**Comment by lNoelia** [comment]
Actualizar el estado de los riesgos, definir el objetivo para dar un riesgo como resuelto y comparar la evolución con esa definicion

**Comment by lNoelia** [comment]
He actualizado el estado de los riesgos, estoy a la espera de respuestas de los miembros del equipo y de la evolución de la semana, por eso esta tarea está al 90%. Se terminará de actualizar el martes antes de la entrega, pero sufrirá modificaciones a lo largo de las dos semanas actualizando el estado de los riesgos.

**Comment by nicsanmen** [comment]
Al igual que Noelia hace una semana, diría que está todo actualizado a falta de algunos datos del resto del equipo que se deben de incluir. Mañana o el martes se editará definitivamente para poder pasarse a PDF y cerrarse, si Noelia lo ve bien también.

**Comment by marolmmar1** [comment]
Para gestionar la disponibilidad y asignación de tareas, propongo poner un EXCEL que recoja los DÍAS de la semana y las  HORAS de los mismos. Cada INTEGRANTE del grupo lo rellena en función de a qué horas está DISPONIBLE durante ese SPRINT. 
Con esta medida podemos mejorar la asignación de tareas y espero que la fluidez a la hora de trabajar en las tareas relativas a las presentaciones.
recordatorio: SE TIENE QUE ACTUALIZAR SEMANALMENTE
