### ISSUE TITLE
Documento de estimación de costes

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#3]
Realización del documento estimación de costes.

Parte de la estimación de costes se ha realizado durante la primera reunión. Pasar dichos cálculos al documento de manera formal para que pueda servir como estimación real.

Los documentos deben respetar una forma y ser redactados con un lenguaje formal. En su mayoría se basan en procesos y actividades de la guía del PMBOK, sin embargo, estamos haciendo una adaptación para las peculiaridades de nuestro proyecto. La decisión sobre secciones y contenido del documento queda a juicio de las personas encargas. El nivel de detalle deberá ser acorde a su impacto proyecto.

*********** 08/02************
Modificar el documento de estimación de acuerdo al feedback de la clase de hoy. Este feedback se podrá encontrar en el documento creado en sharepoint.

**Comment by Josdelsan** [comment]
Hemos hecho una estimación de costes del desarrollo del proyecto, pero en relación a #6 , ¿Tendríamos que tener en cuenta en el precio el coste de despliegue del servicio y los agentes externos de los que dependemos? Creo recordar que a un grupo le preguntaron sobre eso. Si es así eso constituye algunos riesgos que debemos tener en cuenta. Igual lo mejor en ese caso sería hacer una estimación independiente post desarrollo por volumen de cliente(ya que los precios variarán)

@lNoelia @Rick3600

**Comment by Josdelsan** [comment]
Veo muy bien el documento, lo único que me confunde es la parte de seguimiento y control. El desarrollo y seguimiento-control son cosas paralelas, he visto en el documento que el seguimiento y control inicia el el 9 de abril y el desarrollo el 1 de marzo.

Quizás tuviera más sentido poner ambas casi en la misma franja temporal y computar gran parte de esas horas de PM que se indican en desarrollo a seguimiento y control.

**Comment by lNoelia** [comment]
En respuesta a la última revisión @Josdelsan, me gustaría aclarar que "Seguimiento y control"  es simplemente un nombre que se le ha dado a la fase intentando asemejarlo a las fases de PMBOK. Como explico en un comentario en dicho documento, estas fases están sacadas del documento de planificación de la asignatura.   

Mientras que la fase de **"Desarrollo"** se trata de la fase en la cual van a ocurrir los 3 sprints que se hablaron en la primera clase del curso y la fase de **"Seguimiento y Control"** son las semanas dedicadas a la preparación del lanzamiento del producto, en las cuales se puede seguir modificando el producto pero es una fase pensada para diseñar y crear la publicidad del proyecto, preparar los eventos en los cuales el proyecto se va a anunciar y en general dar los últimos retoques, así como hacer un análisis del producto. 

Comprendo que el nombre puede llegar a ser confuso, pero al fin y al cabo son sólo nombres que se pueden cambiar en cualquier momento. ¿Alguna sugerencia sobre cómo llamar a esta fase? 

¡Gracias por el feedback!

**Comment by nicsanmen** [comment]
Entiendo que el nombre de "Seguimiento y Control" pueda resultar confuso si tenemos conocimientos del PMBOK, podemos definirla simplemente como fase de "Preparación de lanzamiento" o algo similar, donde tengamos claro, como dice Noelia, que se pueden seguir retocando cosas de funcionalidad y código, pero es una fase más orientada a dar a conocer el proyecto, hacer marketing, etc.

**Comment by nicsanmen** [comment]
Por otra parte, que lo debería de haber comentado arriba, lo que yo no tengo claro es de donde vienen las estimaciones (y no sé si sería importante mencionarlo en la presentación) es decir, la jusitificación por ejemplo de que estimemos que el PM en la fase de desarrollo del producto va a trabajar 100 horas (entre 3 que somos, claro). Lógicamente van a ser menos horas que en esta fase de preparación, entiendo que simplemente decimos que estas son nuestras estimaciones y que luego compararemos con la realidad para ver el desvío ocasionado no?

**Comment by rosmolarr** [comment]
En lo referente a lo comentado hoy en clase, se deberia tener en cuenta los impuestos **[En el coste faltan los impuestos 6% de impuesto IRPF. Tú pagas impuestos por empleados, pero aparte hay que pagar impuestos por ser una sociedad.]** y tantear añadir un perfil de profesor, no es necesario pero si no se añade hay que saber porque no se añade, p.e: porque eso entra en el perfil de SM. También deberiamos explicar de donde hemos sacado el dinero que le pagamos a cada uno y las horas (si no recuerdo mal las horas si estan argumentadas pero el salario no).
También tantear lo que nos ha dicho el profesor, de que los 28.000 euros del proyecto es algo que nosotros le donamos a las ong, y ya ellas con las donaciones de sus socios nos pagarían las mensualidades para mantener la aplicación. Deberíamos estudiar eso porque es algo que queda muy bonito decir, que nos costaría ese dinero pero que no vamos a cobrarlo porque es nuestra forma de ayudar y aportarle algo bueno a las ongs, y quieras que no eso nos deja en muy buen lugar y se vería que la empresa esta enfocada en ayudar.

**Comment by lNoelia** [comment]
`la jusitificación por ejemplo de que estimemos que el PM en la fase de desarrollo del producto va a trabajar 100 horas (entre 3 que somos, claro)`

He puesto las justificaciones en los comentarios. Estos cálculos se hicieron teniendo en cuenta que no existía el rol de Analista, que se acaba de añadir hoy a esta estimación de costes. Además, se ha tenido en cuenta que no solo las personas con el rol de PM podían hacer tareas que eran para los PM( ya que teníamos en cuenta que reunión con clientes era trabajo de PM). Hemos modificado y justificado las horas por si queréis revisarlo. 


Con respecto a la respuesta de Rosa. `[En el coste faltan los impuestos 6% de impuesto IRPF. Tú pagas impuestos por empleados, pero aparte hay que pagar impuestos por ser una sociedad.]`. Tras consultarlo con una experta, hemos considerado que estos impuestos se deben considerar en el documento de modelo de negocio a la hora de observar el retorno del capital invertido, por tanto no se deben tener en cuenta en el coste del proyecto

**Comment by Josdelsan** [comment]
Podríamos hacer una estimación de cuanto llevamos gastado de dinero para ver los sobrecostes en comparación del burdown de puntos de historia.

**Comment by mansanrod4** [comment]
Para que la diferencia del coste estimado con el ejecutado no sea tan grande deberíamos aclarar qué rol hace cada tarea concretamente. Por ejemplo poner únicamente de analistas a los que han añadido requisitos al DARS. Si se añade el campo rol a las issues y se añade al Clockify con las tags vamos a tener el coste real de forma rápida
