### ISSUE TITLE
Documento de gestión de los usuarios piloto

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/NGOs-documentation#30]
Incidencia anterior: https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/15

**Comment by marinaramirofde** [comment]
Estoy analizando la totalidad de escenarios para descartar los ya probados y estimar los escenarios que se probarán en la encuesta del sprint 2. Algunas tareas no tienen asociado un escenario concreto por lo que procederé a crear uno nuevo para ellas.

**Comment by marinaramirofde** [comment]
Se ha analizado lo del sprint anterior y se ha planificado lo que se realizará para la recogida del feedback del sprint 2.

**Comment by marinaramirofde** [comment]
Se han creado las tablas para rellenar con el feedback según los escenarios repartidos por rol en cada encuesta.
