### ISSUE TITLE
Creación del formulario para los usuarios piloto

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/NGOs-documentation#35]
Se pide crear un formulario para la recogida de información de los usuarios piloto para probar la aplicación. Se recomienda seguir el documento de gestión de usuarios piloto para crearla.

**Comment by rosmolarr** [comment]
A partir del formulario creado por @marinaramirofde , se propone realizar 3 tipos de formularios, uno para las personas mayores, otro para las personas del grupo de tarde, y otro para todos los demas, para que a la hora de probar la aplicación prueben SOLAMENTE el escenario que les toca

**Comment by marinaramirofde** [comment]
Según la actual versión del documento de Gestión de Usuarios Pilotos:

SPRINT 2
P07 E17 (recepción) - Usuarios con pocos 
conocimientos tecnológicos
21/03/2023 24/03/2023
P08 E15, E16, E20, E21 - Representante ONG (BAS) 21/03/2023 24/03/2023
P09 E17 (Envío), - Representante ONG (DM) 21/03/2023 24/03/2023
P10 E20, E21 - Usuarios con 
conocimientos tecnológicos
21/03/2023 24/03/2023
P11 E20, E21 - Usuarios expertos 
tecnológicos
21/03/2023 24/03/2023

---------------------------------------------------

Por lo que tengo una duda:

Aparece una distribución de los escenarios para lo que yo veo mejor dividir en 4 formularios.
1 para mayores
1 para ong1
1 para ong2
1 para expertos y usuarios con conocimientos

Ya que expertos y usuarios con conocimientos tecnológicos comparten escenarios y las ongs no.

¿Lo hago de esa manera o cambio los escenarios para que se realicen 3 formularios? @rosmolarr

**Comment by marinaramirofde** [comment]
Estoy analizando la totalidad de escenarios para descartar los ya probados y estimar los escenarios que se probarán en la encuesta del sprint 2. Algunas tareas no tienen asociado un escenario concreto por lo que procederé a crear uno nuevo para ellas. Una vez estén aclarados los escenarios comenzaré con la creación de las pruebas.

**Comment by marinaramirofde** [comment]
Se ha completado la repartición por roles y se han creado sus formularios. Faltaría validar que todo está bien, completar si hiciera falta y enviar a los usuarios pilotos.
