### ISSUE TITLE
Burndown

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/NGOs-documentation#38]
Se pide crear un mapa de burndown a mano. Para ello primero habría que coger las tareas de las semanas 5 y 6, y para obtener los puntos de historia habría que multiplicar el porcentaje de avance por los puntos de historia. A este total hay que sumarles todas las tareas nuevas de las semanas 7 y 8 con sus puntos de historia. Si alguna tarea de la semana 7 u 8 ya esta empezada y tiene un porcentaje de avance, NO multiplicarlo, poner los puntos de historia completos. 

Teniendo esto buscar, con ayuda del temario dado el dia 15/03, diferentes formas de mostrar el quemado de puntos de historia. Se puede hacer a mano la grafica, o alguna aplicación de internet que lo realice. Nuestro github project no nos da ningun tipo de gráfica de este estilo.

Recapitulando:
- Calcular los puntos de historia totales
- Buscar en el temario o internet sitios donde hacer este tipo de gráficas.
- Empezar a hacerla aunque los PMs vayamos poniendo cuantos puntos se han quemado ese día.

**Comment by lNoelia** [comment]
Cambio el progreso de esta tarea al 90% para indicar que faltan por añadir los puntos de historia completados hoy (20/03) y los de mañana de ser posible (21/03)

**Comment by lNoelia** [comment]
@marolmmar1 El burndown creo que se debería hacer por cada sprint ya que se va a ver mejor. Además en el control del primer sprint pone que no hay ningún punto de historia completado, lo cual no es exacto con la realidad, revisa las issues para ver los cambios de estado que sufrieron y poder actualizar el gráfico.
