### ISSUE TITLE
Documento de impacto legal del proyecto

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/NGOs-documentation#39]
Redactar el documento de "Impacto legal del proyecto", se ha comentado en clase que hay que hacerlo, esperemos que se suba algo a la enseñanza virtual explicando un poco de que va, si no fuera así, coméntanoslo a los PMs el viernes para encontrar una solución.
Fecha límite de esta tarea: lunes día 27/03

**Comment by rosmolarr** [comment]
@marolmmar1 empieza a investigar y ayuda a nico en lo que puedas.

**Comment by nicsanmen** [comment]
Tengo literalmente 0 referencias, además que como aun no se va a nombrar en mucha profundidad en la presentación tampoco, pues menos aun porque no sé ni cómo de importante es. He estado entre ayer y hoy buscando información y demás ejemplos o referencias y he intentado adelantarlo lo máximo posible. De todos modos cualquier feedback o aporte o cualquier cosa es bien recibida. Mañana buscaré más info e intentaré finiquitarlo así más formalmente.

**Comment by nicsanmen** [comment]
He añadido o retocado algunas cosillas y hablado con algún PM para saber qué poner. También he hablado con Marcos para terminar de completarlo puesto que en PSG2 o en PGPI había documentación parecida, vamos a intentar tener un ejemplo para tomarlo como referencia o añadir más cosas.

**Comment by Manueldm01** [comment]
Se debe continuar con el desarrollo de este documento, en clase se ha visto una píldora teórica que se debe revisar puesto que está relacionada.
**Fecha limite: Viernes 7 de abril**

**Comment by marinaramirofde** [comment]
Hemos analizado la píldora teórica así como los ejemplos de empresas como Facebook, Twitter... para una recopilación más profesional.

**Comment by marinaramirofde** [comment]
Ya hemos construido el documento de impacto legal del proyecto, indicando los términos de uso, el sistema de garantía de seguridad, protección de datos, responsabilidades, derechos, etc. Faltaría feedback para los apartados de pagos y responsabilidades de la empresa. Consideramos que el documento está afinado un 80% a falta de confirmación.
