### ISSUE TITLE
Documento de registro de riesgos

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#4]
Realización del documento de registro de riesgos.

Se pretende recopilar los riesgos comentados en la reunión inicial además de los que se vayan identificando. No es necesario definir un plan de acción para los riesgos en detalle.

Los documentos deben respetar una forma y ser redactados con un lenguaje formal. En su mayoría se basan en procesos y actividades de la guía del PMBOK, sin embargo, estamos haciendo una adaptación para las peculiaridades de nuestro proyecto. La decisión sobre secciones y contenido del documento queda a juicio de las personas encargas. El nivel de detalle deberá ser acorde a su impacto proyecto.

**Comment by rosmolarr** [comment]
Ampliación y mejora del documento de riesgos.

- [x] Actualizar el documento para que tenga indice, versiones, resumen ejecutivo, introducción..
- [x] Afinar a tabla de requisitos, se nos ha dicho que nos centremos sobre todo en los negativos asi que partimos de esa base
- [x] Se debería hablar en el documento también sobre como hemos obtenido estos riesgos, que herramientas hemos usado, en que nos hemos basado, etc.

**Comment by rosmolarr** [comment]
- [ ] Añadir nuevos riesgos más concretos. 

- [ ] Añadir un nuevo apartado explicando la manera en la que vamos a cuantificar cómo llevamos el control de los riesgos acontecidos, y si está funcionando el plan de acción y cómo actuar en caso de que no. Todo esto de cara.

- [ ] Los planes de acción no deben ser generales, debe ser una respuesta especifica.

**Comment by lNoelia** [comment]
Como comentamos en la reunión del domingo, he añadido la información del seguimiento de los riesgos a las plantillas de "informe de riesgos". Por favor, revisad este documento. 

Además, he añadido un comentario al documento de Registro de Riesgos en el que expongo varios riesgos que creo que hemos obviado o dejado de lado y tendríamos que evaluarlos. Cambio la Issue a "In progress" para que alguno de los encargados se encargue de realizar este pequeño cambio.

**Comment by Josdelsan** [comment]
Se seguirán añadiendo riesgos pero se cierra la incidencia de definición del documento.
