### ISSUE TITLE
Retrospectiva

### ISSUE THREAD

**Issue by rosmolarr** [ISPP-2023-NGO-P3/NGOs-documentation#48]
Análisis en profundidad de la retrospectiva, problemas que hemos tenido, evolución de los problemas ,medición de los problemas, impacto en el equipo y en el proyecto, probabilidad, problemas que no habíamos identificado ¿han ocurrido?, añadir en el las reuniones de retrospectiva.
**Fecha limite: Sábado 8 de abril a las 23:59**

**Comment by Manueldm01** [comment]
El documento de retrospectiva está acabado, solo falta revisarlo antes de la entrega en busca de algún error y añadir el Niko Niko antes de entregarlo.
