### ISSUE TITLE
Documento de modelo de negocio

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#6]
Explicar el modelo de negocio de la organización (tendremos que pensarlo bien) y aplicar todo el feedback respecto al análisis de competidores.

**Comment by Josdelsan** [comment]
Añadir plan de precios  haciendo una estimación positiva y otra negativa. Hacer a ser posible una tabla para que quede lo más claro posible tanto el modelo de negocio ya que puede resultar confuso como el plan de precios.

El tema de los módulos los mencionaría y dejaría el trabajo de definición a los encargados de los requisitos. La idea es simplificar lo que tenemos pero no quitarle el sentido.

Ejemplo de pregunta para sacar conclusiones: ¿Cuántas persona de soporte técnico/código harían falta para mantener una base de cliente que suponga el 2.5% de las ONGs de España? ¿Cuánto estarían dispuestos a pagar nuestros cliente?

@Rick3600 @lNoelia

**Comment by lNoelia** [comment]
> Ejemplo de pregunta para sacar conclusiones: ¿Cuántas persona de soporte técnico/código harían falta para mantener una base de cliente que suponga el 2.5% de las ONGs de España? ¿Cuánto estarían dispuestos a pagar nuestros cliente?

En respuesta a la primera pregunta, haciendo un estudio sobre las ONGs de España y el tipo de ONGs que son, concluimos que alrededor de un 15/20% de las ONGs podían estar interesadas en un producto como el que queremos desarrollar. Para hacer un cálculo de costes, concluimos que un 5% del total de las ONGs podrían ser potenciales clientes teniendo en cuenta que nuestra aplicación podría interesar a otros tipos de clientes como pequeñas y medianas empresas que puedan requerir de alguno de los módulos que ofrecemos. 

En respuesta a la segunda pregunta, los encargados del documento concluimos que comunicarnos con los clientes sobre este tema podría llegar a ser confuso dada los requisitos impuestos por las ONGs, que requieren (y se les ofreció) una aplicación gratuita. Es esta la razón por la cual no se ha comunicado a los clientes esta pregunta.

**Comment by Josdelsan** [comment]
Hay que añadir varias variables a nuestro modelo de negocio y ajustar los precios acorde:

Hacer un apartado **estimaciones** de distintos números de ONGs que quisieran el servicio (sólo las nuestras, un 5% ONGs de Sevilla, 2.5% de España, 5% España, 10% España). Se podría incluso un caso donde **organizaciones en general** no solo ONGs (Hay muchas más en proporción y también podrían ser clientes potenciales).

En ese caso, ¿Cuánto tendríamos que cobrar para manteniendo los sueldos del soporte (ajustar cantidad de personal necesario) **recuperar la inversión** en 1,2 ó 4 años? Habría que añadir a lo anterior el interés de un posible **préstamo** para afrontar el desarrollo. También hay que tener en cuenta junto a los sueldos el coste de **mantenimiento de los servicios** a nivel técnico, ¿Debemos hacer **outsourcing** de los servidores(es lo más cómodo supongo)?, ¿Cuánto nos cuesta levantar la **instancia para cada cliente**?

Hacer una **tabla comparativa** donde compare **número de organizaciones contra años de retorno** y exponga el precio que tendrían que pagar los clientes mensualmente (van a salir valores muy locos desde miles de euros hasta pocos euros, esa es la gracia). La tabla ayudará a elegir la mejor opción.

Todo esto irá avalado por #16 

A parte darle un formato de numeración con subsecciones numéricas y usad los títulos para mejor identificación de las partes. Probablemente creemos un documento a parte para incluir el estudio de competidores como anexo.

**Comment by lNoelia** [comment]
Hemos hecho un estudio de la recuperación de la inversión teniendo en cuenta el crecimiento de clientes desde el 1% de las ONGs de España hasta llegar a un 7,5% de las ONGs en 5 trimestres. De momento creemos que el documento está acabado pero necesitamos confirmación. Revisadlo please

**Comment by rosmolarr** [comment]
Añadir gráficas (diagrama de barras, temporal…) para mostrar todos los datos que conseguisteis del estudio, de cara a incluirlas en la presentación. Intentar que sean lo más explicativas posibles para que se puedan enseñar durante 1 minuto y pueda verse claro y conciso. Para ello incluir sólo los datos más relevantes.

**Comment by Josdelsan** [comment]
Se propone revisar el feedback de la sesión del día 1/03 y completar el documento de competidores con los nuevos dados de cara a enviarlo por correo a los profesores.

**Comment by rosmolarr** [comment]
En esta nueva semana se propone buscar y redactar las diferencias de nuestra organización con los distintos competidores, manteniendo el documento vivo y actualizado.

**Comment by lNoelia** [comment]
Esta semana se propone: buscar y redactar las diferencias de nuestra organización con los distintos competidores, manteniendo el documento vivo y actualizado. ( Intentar que sean al menos 2/3) 
Además, se busca hacer un análisis del retorno de los gastos con una aproximación pesimista, optimista y estimada(creo que la que está se puede considerar estimada) 😄

**Comment by cardelbec** [comment]
He metido las diferencias de nuestra organización con los competidores que no lo tenían, y he añadido un nuevo competidor (TeamKinetic) para que se pueda poner en la presentación de la semana que viene.

**Comment by Rick3600** [comment]
Ya se ha realizado la aproximación pesimista y optimista, además de la grafica producto de la suma de las 3 estimaciones

**Comment by lNoelia** [comment]
Si tenéis tiempo esta semana intentad buscar algún competidor más, de momento todo perfecto 👍

**Comment by cardelbec** [comment]
He añadido un competidor nuevo (InitLive) para cumplir el objetivo propuesto en el documento de riesgos.

**Comment by lNoelia** [comment]
Para la semana 8 se debe añadir 2 nuevos competidores para seguir con las buenas prácticas y dar por finalizado el riesgo acontecido

**Comment by Rick3600** [comment]
Competidores VolunteerHub y Cervistech analizados y añadido.
