### ISSUE TITLE
Analisis de costes

### ISSUE THREAD

**Issue by lNoelia** [ISPP-2023-NGO-P3/NGOs-documentation#63]

**Comment by lNoelia** [comment]
- Analizar el coste actual vs el presupuesto para actualizar de alguna manera el presupuesto. ( por ejemplo modificar las reservas de contingencia , estructuras, las horas dedicadas por cada rol etc etc etc )
- Preparar varios planes de inversión para poder poner en los anuncios 

Fecha límite Sábado 15 23:59 horas.

**Comment by rubsuadav** [comment]
Realizada la tarea de documentación habiendo creado nueva documento de estimación de costes e introducido un nuevo apartado en el modelo de negocio
