### ISSUE TITLE
Analizar costes del marketing

### ISSUE THREAD

**Issue by Manueldm01** [ISPP-2023-NGO-P3/NGOs-documentation#68]
Hacer en el documento Plan de Marketing una sección donde se recojan los costes relacionados con el marketing.

**Comment by mansanrod4** [comment]
He añadido lo que llevamos invertido en marketing, antes de la entrega añado lo que falta.
![image](https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/assets/44496070/38c5f025-ed2e-4262-9057-9b07476b80e9)

**Comment by mansanrod4** [comment]
No se ha añadido ningún coste más.
