### ISSUE TITLE
Plan de traccion

### ISSUE THREAD

**Issue by Manueldm01** [ISPP-2023-NGO-P3/NGOs-documentation#75]
Redactar un documento que recoja de que forma vamos a ganar tracción en el mercado, con colaboraciones, ofertas... en la teoría hay más información sobre esto.

**Comment by lNoelia** [comment]
Comunicarse con Manuel S, tiene una tarea para profundizar en el SEO y pienso que estas dos tareas pueden ir de la mano #78

**Comment by cardelbec** [comment]
Daily: versión inicial de documento con secciones de introducción y algunas estrategias para ganar tracción.

**Comment by cardelbec** [comment]
Daily: he terminado el documento, con lo que se explicó en la píldora teórica y lo que hay en el plan de marketing no se me ocurre nada más que poner en lo que a estrategias para ganar tracción respecta.
