### ISSUE TITLE
Analisis de competidores

### ISSUE THREAD

**Issue by Manueldm01** [ISPP-2023-NGO-P3/NGOs-documentation#76]

**Comment by lNoelia** [comment]
Seguir el modelo de negocio, y buscar al menos 2 competidores

**Comment by rubsuadav** [comment]
Estado de la issue: he encontrado un nuevo competidor llamado Blackbaud que tiene bastante competencia acorde a nuestro modelo de negocio, este ofrece estos servicios: gestión de donaciones, gestión de eventos, gestión de voluntarios y gestión de membresía.
Para más información véase documento de Modelo de Negocio punto 4.2.19
