### ISSUE TITLE
Profundizar SEO ( dentro del plan de marketing)

### ISSUE THREAD

**Issue by Manueldm01** [ISPP-2023-NGO-P3/NGOs-documentation#78]

**Comment by lNoelia** [comment]
Esta tarea debe hacerse en el documento del plan de marketing, se divide debido a la complejidad de la documentación. Profundizar sobre el documento de planificacion de marketing ( el documento realizado la semana anterior por marina) y comunicar con la tarea del plan de traccion issue #75

**Comment by mansanrod4** [comment]
He añadido detalles en lo que había ya en el plan de marketing. Más o menos este es el resumen del plan:
1. Cómo elegir keywords.
2. Optimizar la landing page: https://github.com/ISPP-2023-NGO-P3/NGOs-documentation/issues/19 analizando el antes/después de la optimización. Además de añadir enlaces a la landing page desde las 3 apps desarrolladas.
3. Solicitar colaboración para tener más backlinks

Lo dejo en revisión, en cuanto esté actualizada la landing lo termino.
