### ISSUE TITLE
Definir plan de formación del equipo de desarrollo

### ISSUE THREAD

**Issue by Josdelsan** [ISPP-2023-NGO-P3/NGOs-documentation#9]

**Comment by Josdelsan** [comment]
Hay que hacer un documento con algunas guías básicas de las tecnologías a usar (spring y react). Quizás unas nociones básicas de como funciona cada framework, sobre todo como es la estructura de un proyecto con React(que es un componente, una página, etc)

Comentar también que vamos a aprovechar herramientas como Github Copilot, ChatGPT y IntelliCode para el desarrollo. El entorno de desarrollo por defecto va a ser VSCode, necesitamos saber que extensiones serán de ayuda para el desarrollo

El documento no tiene que ser formal, mientras tenga los enlaces bien claro de que es cada cosa es suficiente.

@rubsuadav

**Comment by rubsuadav** [comment]
Vale yo se de un par de extensiones muy buenas también para react. Una de ellas es un formateador de código al pulsar las teclas ALT, SFHIFT F que se llama **Prettier**.

La otra extensión nos ayuda con el código de react, se llama **ES7+ React/Redux/React-Native snippets**. 
Ambas son gratuitas y son muy usadas por programadores react. 

No se si te parecen buenas o no pero yo las conozco porque en el tutorial que me ví de react las usaba.

@Josdelsan

**Comment by Josdelsan** [comment]
Todas esas cosas están perfectas. Tendremos que procurar que todo nuestro ciclo de desarrollo e integración continua siga unas convenciones de como se escribe el código, comentarios, etc. 

Todo lo que sean cosas como formateadores, Linters y sean fácilmente instalables perfecto. Tampoco pasándonos paro no tener entornos desarrollo mastodónticos.

@rubsuadav

**Comment by rubsuadav** [comment]
Perfecto, voy a crear el documento pues y vamos redactándolo todas las ideas estas para que se vea reflejado.
